### ISSUE TITLE
Fig Compatibility

### ISSUE THREAD

**Issue by thedug** [SeerUK/OSXContainerHost#2] opened 2015-01-30 23:34 UTC
Have you ever used fig volumes with your vagrant image?

I've been using boot2docker and performance is terrible, so I've been working on setting up Vagrant/NFS rather than relying on the VBoxFS. 

I tried another Vagrant/Boot2Docker fork but the volumes don't mount. 

Thought I would ping you in case you've already tried it.

**Comment by SeerUK** [comment] 2015-02-07 17:01
I've not actually tried it, no. I do understand that handling volumes (and the filesystem in general) is tricky with Docker on OS X.

I'm actually only using Docker in production now, rather than in development, as it seems to work much easier that way.

Sorry this is a week later, I've been very busy with work!

**Comment by vsolovyov** [comment] 2015-02-11 10:24
We're using this with fig and it actually works.

The only problem we're running into is the problem with `devicemapper` like this:

```Service 'migrations' failed to build: Error getting container 904bfffe74024ca9a29d5f077b6d44230ab8e8a4990f7ccd254055d8d2fe8b0d from driver devicemapper: Error mounting '/dev/mapper/docker-8:1-263156-904bfffe74024ca9a29d5f077b6d44230ab8e8a4990f7ccd254055d8d2fe8b0d' on '/var/lib/docker/devicemapper/mnt/904bfffe74024ca9a29d5f077b6d44230ab8e8a4990f7ccd254055d8d2fe8b0d': no such file or directory```

When I'm building an image from Dockerfile it actually occurs at every other step. It doesn't happen with boot2docker, because boot2docker uses AUFS. So it would be very useful if this project used AUFS too, as it gets a little boring and slow to restart build for every other step.

**Comment by SeerUK** [comment] 2015-02-11 10:39
I'll see if I get some time to look into using AUFS. Is there a publicly available Docker image / Fig configuration that you know does this that I can use to test this issue with?

**Comment by vsolovyov** [comment] 2015-02-11 11:14
Not that I know of, but if I'll find something or make it myself, I will certainly notify you

**Comment by gmorse81** [comment] 2015-02-14 17:55
I am having this same issue. It seems that when a dockerfile uses the COPY command, then RUNs a command against the file that was just copied, docker does not see the newly created container (since it chains container builds together when it builds). Not sure this is specific to fig, but it also happening for me when running fig up to build and orchestrate a set of containers.

**Comment by SeerUK** [comment] 2015-03-03 10:21
Hi folks. I've just pushed a couple of small changes, and am hoping that the issue is resolved. I have since tried a fig setup using this on my MacBook Pro, and it all worked fine - I just let it do it's thing and it got the whole way through without a hiccup.

Please update your copy from this repo and give it another shot and see if you still encounter any issues please.

Also - I made it a little easier to configure the CPU count and memory of the machine, just specify the values you want in environment variables `OCH_CPUS` and `OCH_MEMORY`.

**Comment by mewm** [comment] 2015-03-04 22:30
Now when docker-compose has replaced fig, I'm not experiencing the devicemapper issue anymore.

**Comment by SeerUK** [comment] 2015-03-05 09:11
Great stuff! :) I'll have to actually give compose a try tonight. I'm going to close this for now though.

**Closed by SeerUK** 2015-03-05 09:11 UTC

**Comment by mewm** [comment] 2015-03-05 13:11
@SeerUK Because I miss-configured disqus on my blog, your comments has been removed on my bog :/. The change needed from fig to docker-compose is just to rename the fig.yml to docker-compose.yml and then use the docker-compose runtime. (Check top change: https://github.com/mewm/ghost-mariadb-docker/commit/8e50023d91197312a0f9270e382eb4e9ec4c3d9a )

**Comment by SeerUK** [comment] 2015-03-05 14:09
No worries, thanks for letting me know. I'm glad it's that straightforward! :)

**Comment by SeerUK** [comment] 2015-03-05 14:27
Just tried it out, worked flawlessly with docker-compose. Awesome :)

**Comment by mewm** [comment] 2015-03-05 14:40
Sweet! All safe and sound then :+1:
